# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine
WORKDIR /app
COPY package.json package-lock.json tsconfig.json next.config.js postcss.config.js tailwind.config.js ./
COPY . .
RUN npm install --ignore-scripts && npm run preparepackage
EXPOSE 4000
CMD ["npm", "run", "start:prod"]
